### ISSUE TITLE
Missing VirtualShell library Files

### ISSUE THREAD

**Issue by jordywastaken** [JamesIsWack/Akari---Playstaion-3-VSH-Plugin#1]
It seems you only uploaded the headers of this library, the full source code with every files included can be found here : [https://www.psx-place.com/threads/plugin-akari-new-custom-vsh-menu.36877/#post-347643](https://www.psx-place.com/threads/plugin-akari-new-custom-vsh-menu.36877/#post-347643).

**Comment by JamesIsWack** [comment]
> It seems you only uploaded the headers of this library, the full source code with every files included can be found here : https://www.psx-place.com/threads/plugin-akari-new-custom-vsh-menu.36877/#post-347643.

holy fucking christ i didnt expect you to be back, well welcome. glad you're not mad i essentially stole the project 💀 
anyway, thanks for letting me know. i would like to add some QoL stuff to Akari, we can discuss this on discord if you're free. 
i'll go ahead and send you a friend request, take car

James
